[2022-03-15 13:35:32,989] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [queued]>
[2022-03-15 13:35:33,004] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [queued]>
[2022-03-15 13:35:33,004] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 13:35:33,004] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 13:35:33,004] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 13:35:33,026] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 13:35:00+00:00
[2022-03-15 13:35:33,030] {standard_task_runner.py:52} INFO - Started process 24311 to run task
[2022-03-15 13:35:33,039] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T13:35:00+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpxfnyu2gh', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp_oq1vac5']
[2022-03-15 13:35:33,043] {standard_task_runner.py:77} INFO - Job 315: Subtask to_sql
[2022-03-15 13:35:33,168] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 13:35:33,227] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T13:35:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T13:35:00+00:00
[2022-03-15 13:35:33,247] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 13:35:33,248] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 13:35:34,110] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 13:35:34,111] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 13:35:34,669] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 157, in to_sql
    dfs.append(pd.DataFrame.from_dict(data)) # append the data frame to the list
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 1593, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2022-03-15 13:35:34,682] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=to_sql, execution_date=20220315T133500, start_date=20220315T183532, end_date=20220315T183534
[2022-03-15 13:35:34,695] {standard_task_runner.py:89} ERROR - Failed to execute job 315 for task to_sql
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 157, in to_sql
    dfs.append(pd.DataFrame.from_dict(data)) # append the data frame to the list
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 1593, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2022-03-15 13:35:34,739] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 13:35:34,762] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-15 13:36:57,387] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [queued]>
[2022-03-15 13:36:57,400] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [queued]>
[2022-03-15 13:36:57,400] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 13:36:57,400] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 13:36:57,400] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 13:36:57,412] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 13:35:00+00:00
[2022-03-15 13:36:57,417] {standard_task_runner.py:52} INFO - Started process 24356 to run task
[2022-03-15 13:36:57,424] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T13:35:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp4b4qo0_4', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpm37egcyb']
[2022-03-15 13:36:57,429] {standard_task_runner.py:77} INFO - Job 313: Subtask to_sql
[2022-03-15 13:36:57,494] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T13:35:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 13:36:57,544] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T13:35:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T13:35:00+00:00
[2022-03-15 13:36:57,563] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 13:36:57,564] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 13:36:58,121] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 13:36:58,122] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 13:36:58,628] {logging_mixin.py:109} INFO - {'title': 'Greek-Style Baked Fish: Fresh, Simple, and Delicious', 'servings': 4, 'summary': 'You can never have too many main course recipes, so give Greek-Style Baked Fish: Fresh, Simple, and Delicious a try. For <b>$3.04 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. This recipe makes 4 servings with <b>345 calories</b>, <b>28g of protein</b>, and <b>12g of fat</b> each. This recipe is liked by 396 foodies and cooks. Head to the store and pick up salt & pepper, pepper, wine, and a few other things to make it today. To use up the cooked rice you could follow this main course with the <a href="https://spoonacular.com/recipes/breakfast-rice-pudding-547155">Breakfast Rice Pudding</a> as a dessert. From preparation to the plate, this recipe takes about <b>30 minutes</b>. It is a good option if you\'re following a <b>gluten free and pescatarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/simple-greek-style-baked-fish-557560">Simple Greek Style Baked Fish</a>, <a href="https://spoonacular.com/recipes/greek-style-baked-fish-526858">Greek Style Baked Fish</a>, and <a href="https://spoonacular.com/recipes/delicious-greek-pastitsio-casserole-style-569500">Delicious Greek Pastitsio {Casserole-Style}</a>.', 'diets': ['gluten free', 'pescatarian'], 'equipment': ['baking pan', 'oven'], 'ingredients': ['bell pepper', 'tomato', 'lemon wedge', 'red onion', 'white wine', 'dried basil', 'cooked rice', 'pepper', 'fish', 'feta cheese', 'olive oil', 'cooking spray', 'oregano', 'fresh basil', 'fish fillets', 'salt and pepper'], 'id': 716408.0}
[2022-03-15 13:36:58,629] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 158, in to_sql
    print(pd.DataFrame.from_dict(data))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 1593, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2022-03-15 13:36:58,640] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=to_sql, execution_date=20220315T133500, start_date=20220315T183657, end_date=20220315T183658
[2022-03-15 13:36:58,652] {standard_task_runner.py:89} ERROR - Failed to execute job 313 for task to_sql
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 158, in to_sql
    print(pd.DataFrame.from_dict(data))
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 1593, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 635, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
[2022-03-15 13:36:58,680] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 13:36:58,699] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
