[2022-03-14 14:05:46,621] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [queued]>
[2022-03-14 14:05:46,629] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [queued]>
[2022-03-14 14:05:46,629] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 14:05:46,629] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 14:05:46,629] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 14:05:46,639] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): upload_to_bucket> on 2022-03-14 14:10:00+00:00
[2022-03-14 14:05:46,642] {standard_task_runner.py:52} INFO - Started process 86979 to run task
[2022-03-14 14:05:46,650] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'upload_to_bucket', 'scheduled__2022-03-14T14:10:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpx40wyxu4', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpwa7m4xwm']
[2022-03-14 14:05:46,653] {standard_task_runner.py:77} INFO - Job 185: Subtask upload_to_bucket
[2022-03-14 14:05:46,710] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 14:05:46,760] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=upload_to_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T14:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T14:10:00+00:00
[2022-03-14 14:05:46,764] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 28, in upload_to_bucket
    data = json.load(f)
  File "/opt/anaconda3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-03-14 14:05:46,774] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=upload_to_bucket, execution_date=20220314T141000, start_date=20220314T190546, end_date=20220314T190546
[2022-03-14 14:05:46,786] {standard_task_runner.py:89} ERROR - Failed to execute job 185 for task upload_to_bucket
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 28, in upload_to_bucket
    data = json.load(f)
  File "/opt/anaconda3/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/anaconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-03-14 14:05:46,829] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-14 14:05:46,850] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 14:13:50,744] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [queued]>
[2022-03-14 14:13:50,752] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [queued]>
[2022-03-14 14:13:50,752] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 14:13:50,752] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 14:13:50,752] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 14:13:50,761] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): upload_to_bucket> on 2022-03-14 14:10:00+00:00
[2022-03-14 14:13:50,765] {standard_task_runner.py:52} INFO - Started process 87289 to run task
[2022-03-14 14:13:50,770] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'upload_to_bucket', 'scheduled__2022-03-14T14:10:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp78uo7jaz', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpzlj4c674']
[2022-03-14 14:13:50,774] {standard_task_runner.py:77} INFO - Job 180: Subtask upload_to_bucket
[2022-03-14 14:13:50,826] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-14T14:10:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 14:13:50,874] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=upload_to_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T14:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T14:10:00+00:00
[2022-03-14 14:13:50,894] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-14 14:13:50,895] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-14 14:13:54,448] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 14:13:54,460] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=upload_to_bucket, execution_date=20220314T141000, start_date=20220314T191350, end_date=20220314T191354
[2022-03-14 14:13:54,505] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 14:13:54,527] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
