[2022-03-14 12:10:58,352] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:10:58,360] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:10:58,360] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:10:58,360] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:10:58,360] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:10:58,371] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:12:00+00:00
[2022-03-14 12:10:58,375] {standard_task_runner.py:52} INFO - Started process 82774 to run task
[2022-03-14 12:10:58,382] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:12:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpcdkvoxsl', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpeap7pgmb']
[2022-03-14 12:10:58,386] {standard_task_runner.py:77} INFO - Job 141: Subtask request_user
[2022-03-14 12:10:58,451] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:10:58,507] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:12:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:12:00+00:00
[2022-03-14 12:10:58,618] {logging_mixin.py:109} INFO - {'pantry': {'excludeIngredients': ['kidney beans'], 'includeIngredients': ['cooking oil', 'salt', 'chickpeas'], 'intolerances': 'dairy'}, 'user': {'address': '885 Stephanie Hills\nSouth Susan, IA 83064', 'description': 'Can go night less light technology. Professional since kid audience daughter mouth catch.\nAnything low by network boy ground stand. Admit indicate know administration what this which.', 'name': 'Jaime Nicholson'}}
[2022-03-14 12:10:58,619] {logging_mixin.py:109} INFO - /Users/HomeFolder/mydatasets/datacourse_data-workflows-and-architectures/miniprojects/airflow
[2022-03-14 12:11:00,621] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 12:11:00,631] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121200, start_date=20220314T171058, end_date=20220314T171100
[2022-03-14 12:11:00,672] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 12:11:00,692] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 12:14:46,080] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:14:46,085] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:14:46,086] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:14:46,086] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:14:46,086] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:14:46,094] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:12:00+00:00
[2022-03-14 12:14:46,097] {standard_task_runner.py:52} INFO - Started process 82901 to run task
[2022-03-14 12:14:46,103] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:12:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpckdbdg0h', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpk9x30es9']
[2022-03-14 12:14:46,105] {standard_task_runner.py:77} INFO - Job 152: Subtask request_user
[2022-03-14 12:14:46,152] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:14:46,190] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:12:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:12:00+00:00
[2022-03-14 12:14:46,294] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:14:46,303] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121200, start_date=20220314T171446, end_date=20220314T171446
[2022-03-14 12:14:46,314] {standard_task_runner.py:89} ERROR - Failed to execute job 152 for task request_user
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:14:46,328] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-14 12:14:46,346] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 12:16:16,518] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:16:16,526] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [queued]>
[2022-03-14 12:16:16,526] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:16:16,526] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:16:16,526] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:16:16,535] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:12:00+00:00
[2022-03-14 12:16:16,539] {standard_task_runner.py:52} INFO - Started process 82986 to run task
[2022-03-14 12:16:16,544] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:12:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpzhvyqq7x', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpimq7sflc']
[2022-03-14 12:16:16,548] {standard_task_runner.py:77} INFO - Job 151: Subtask request_user
[2022-03-14 12:16:16,599] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:12:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:16:16,645] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:12:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:12:00+00:00
[2022-03-14 12:16:18,770] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 12:16:18,779] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121200, start_date=20220314T171616, end_date=20220314T171618
[2022-03-14 12:16:18,824] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 12:16:18,846] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
