[2022-03-14 12:10:46,360] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [queued]>
[2022-03-14 12:10:46,370] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [queued]>
[2022-03-14 12:10:46,371] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:10:46,371] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:10:46,371] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:10:46,383] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:10:00+00:00
[2022-03-14 12:10:46,387] {standard_task_runner.py:52} INFO - Started process 82765 to run task
[2022-03-14 12:10:46,394] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:10:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpb62a9qbk', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp7plb6t9n']
[2022-03-14 12:10:46,398] {standard_task_runner.py:77} INFO - Job 138: Subtask request_user
[2022-03-14 12:10:46,467] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:10:46,532] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:10:00+00:00
[2022-03-14 12:10:46,676] {logging_mixin.py:109} INFO - {'pantry': {'excludeIngredients': ['ginger', 'escargot'], 'includeIngredients': ['escargot', 'tomato', 'cauliflower rice', 'sweet potato'], 'intolerances': 'dairy'}, 'user': {'address': '4686 Jennifer Ferry Suite 818\nSavagefurt, MI 35647', 'description': 'Generation free some.\nSupport year anyone few class summer. Live treatment statement seat. Sometimes write or miss.\nPolice report remain certain. Bank change play whom.', 'name': 'Warren Morse'}}
[2022-03-14 12:10:46,678] {logging_mixin.py:109} INFO - /Users/HomeFolder/mydatasets/datacourse_data-workflows-and-architectures/miniprojects/airflow
[2022-03-14 12:10:48,681] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 12:10:48,690] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121000, start_date=20220314T171046, end_date=20220314T171048
[2022-03-14 12:10:48,728] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 12:10:48,750] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 12:14:40,488] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [queued]>
[2022-03-14 12:14:40,495] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [queued]>
[2022-03-14 12:14:40,496] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:14:40,496] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:14:40,496] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:14:40,505] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:10:00+00:00
[2022-03-14 12:14:40,509] {standard_task_runner.py:52} INFO - Started process 82892 to run task
[2022-03-14 12:14:40,515] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:10:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp8uj_x5n1', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpzmnbhlrt']
[2022-03-14 12:14:40,518] {standard_task_runner.py:77} INFO - Job 150: Subtask request_user
[2022-03-14 12:14:40,571] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:10:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:14:40,615] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:10:00+00:00
[2022-03-14 12:14:40,743] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:14:40,753] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121000, start_date=20220314T171440, end_date=20220314T171440
[2022-03-14 12:14:40,764] {standard_task_runner.py:89} ERROR - Failed to execute job 150 for task request_user
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:14:40,790] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-14 12:14:40,811] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
