[2022-03-15 21:12:10,220] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-15T21:12:00+00:00 [queued]>
[2022-03-15 21:12:10,228] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-15T21:12:00+00:00 [queued]>
[2022-03-15 21:12:10,228] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 21:12:10,228] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 21:12:10,228] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 21:12:10,238] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): upload_to_bucket> on 2022-03-15 21:12:00+00:00
[2022-03-15 21:12:10,242] {standard_task_runner.py:52} INFO - Started process 38940 to run task
[2022-03-15 21:12:10,249] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'upload_to_bucket', 'scheduled__2022-03-15T21:12:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmph2wbtk7d', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp2j9suvu2']
[2022-03-15 21:12:10,253] {standard_task_runner.py:77} INFO - Job 405: Subtask upload_to_bucket
[2022-03-15 21:12:10,313] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.upload_to_bucket scheduled__2022-03-15T21:12:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 21:12:10,371] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=upload_to_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T21:12:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T21:12:00+00:00
[2022-03-15 21:18:09,004] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 38940. PIDs of all processes in the group: [38940]
[2022-03-15 21:18:09,010] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 38940
[2022-03-15 21:18:09,011] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-15 21:18:09,041] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 72, in upload_to_bucket
    f = open(file)
  File "/opt/anaconda3/lib/python3.9/_bootlocale.py", line 33, in getpreferredencoding
    def getpreferredencoding(do_setlocale=True):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-15 21:18:09,060] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=upload_to_bucket, execution_date=20220315T211200, start_date=20220316T021210, end_date=20220316T021809
[2022-03-15 21:18:09,094] {standard_task_runner.py:89} ERROR - Failed to execute job 405 for task upload_to_bucket
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 72, in upload_to_bucket
    f = open(file)
  File "/opt/anaconda3/lib/python3.9/_bootlocale.py", line 33, in getpreferredencoding
    def getpreferredencoding(do_setlocale=True):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-15 21:18:09,113] {process_utils.py:70} INFO - Process psutil.Process(pid=38940, status='terminated', exitcode=1, started='21:12:10') (38940) terminated with exit code 1
