[2022-03-14 12:11:13,683] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:11:13,690] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:11:13,690] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:11:13,690] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:11:13,690] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:11:13,699] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:16:00+00:00
[2022-03-14 12:11:13,703] {standard_task_runner.py:52} INFO - Started process 82784 to run task
[2022-03-14 12:11:13,708] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:16:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpxx5hbj0m', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp_05adcmc']
[2022-03-14 12:11:13,711] {standard_task_runner.py:77} INFO - Job 144: Subtask request_user
[2022-03-14 12:11:13,768] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:11:13,819] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:16:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:16:00+00:00
[2022-03-14 12:11:13,930] {logging_mixin.py:109} INFO - {'pantry': {'excludeIngredients': ['salt'], 'includeIngredients': ['lime', 'chickpeas', 'onion', 'water'], 'intolerances': 'peanut'}, 'user': {'address': '550 Nichols Isle Suite 592\nCookmouth, DC 28172', 'description': 'Address charge right help exactly beat meet exist. Conference marriage sit eight concern responsibility forward main. Pass now cup war event seek include. Various treatment arm mouth tax check dream.', 'name': 'Jeremy Gallegos'}}
[2022-03-14 12:11:13,931] {logging_mixin.py:109} INFO - /Users/HomeFolder/mydatasets/datacourse_data-workflows-and-architectures/miniprojects/airflow
[2022-03-14 12:11:15,933] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 12:11:15,943] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121600, start_date=20220314T171113, end_date=20220314T171115
[2022-03-14 12:11:16,007] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 12:11:16,027] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 12:15:01,533] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:15:01,541] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:15:01,541] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:15:01,541] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:15:01,541] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:15:01,551] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:16:00+00:00
[2022-03-14 12:15:01,554] {standard_task_runner.py:52} INFO - Started process 82923 to run task
[2022-03-14 12:15:01,561] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:16:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmprld9_rbu', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp6tugmffo']
[2022-03-14 12:15:01,564] {standard_task_runner.py:77} INFO - Job 156: Subtask request_user
[2022-03-14 12:15:01,620] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:15:01,667] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:16:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:16:00+00:00
[2022-03-14 12:15:01,798] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:15:01,809] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121600, start_date=20220314T171501, end_date=20220314T171501
[2022-03-14 12:15:01,821] {standard_task_runner.py:89} ERROR - Failed to execute job 156 for task request_user
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 19, in request_user
    json.dump(json_data, json_file)
NameError: name 'json' is not defined
[2022-03-14 12:15:01,832] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-14 12:15:01,853] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-14 12:16:29,720] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:16:29,729] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [queued]>
[2022-03-14 12:16:29,729] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:16:29,729] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 12:16:29,729] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 12:16:29,738] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): request_user> on 2022-03-14 12:16:00+00:00
[2022-03-14 12:16:29,741] {standard_task_runner.py:52} INFO - Started process 82996 to run task
[2022-03-14 12:16:29,747] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'request_user', 'scheduled__2022-03-14T12:16:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp8vgwkzb8', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmp5uvjv7hf']
[2022-03-14 12:16:29,750] {standard_task_runner.py:77} INFO - Job 154: Subtask request_user
[2022-03-14 12:16:29,806] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.request_user scheduled__2022-03-14T12:16:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-14 12:16:29,853] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=request_user
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T12:16:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-14T12:16:00+00:00
[2022-03-14 12:16:31,965] {python.py:175} INFO - Done. Returned value was: None
[2022-03-14 12:16:31,975] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=simple_dag, task_id=request_user, execution_date=20220314T121600, start_date=20220314T171629, end_date=20220314T171631
[2022-03-14 12:16:32,027] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 12:16:32,049] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
