[2022-03-15 15:28:44,955] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:23:17.494685+00:00 [queued]>
[2022-03-15 15:28:44,964] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:23:17.494685+00:00 [queued]>
[2022-03-15 15:28:44,964] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:28:44,964] {taskinstance.py:1244} INFO - Starting attempt 2 of 1
[2022-03-15 15:28:44,964] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 15:28:44,974] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): to_sql> on 2022-03-15 15:23:17.494685+00:00
[2022-03-15 15:28:44,978] {standard_task_runner.py:52} INFO - Started process 28454 to run task
[2022-03-15 15:28:44,984] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'to_sql', 'scheduled__2022-03-15T15:23:17.494685+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmprp5xvyas', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpb0o3p_ky']
[2022-03-15 15:28:44,988] {standard_task_runner.py:77} INFO - Job 351: Subtask to_sql
[2022-03-15 15:28:45,051] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.to_sql scheduled__2022-03-15T15:23:17.494685+00:00 [running]> on host MacBook-Pro.local
[2022-03-15 15:28:45,096] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=to_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T15:23:17.494685+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T15:23:17.494685+00:00
[2022-03-15 15:30:46,044] {local_task_job.py:191} WARNING - The recorded hostname MacBook-Pro.local does not match this instance's hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 15:30:46,062] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 28454. PIDs of all processes in the group: [28454]
[2022-03-15 15:30:46,062] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 28454
[2022-03-15 15:31:46,098] {process_utils.py:138} WARNING - process psutil.Process(pid=28454, name='python3.9', status='running', started='15:28:44') did not respond to SIGTERM. Trying SIGKILL
[2022-03-15 15:31:46,098] {process_utils.py:75} INFO - Sending the signal Signals.SIGKILL to group 28454
[2022-03-15 15:31:46,107] {process_utils.py:70} INFO - Process psutil.Process(pid=28454, name='python3.9', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:28:44') (28454) terminated with exit code Negsignal.SIGKILL
[2022-03-15 15:31:46,112] {standard_task_runner.py:133} ERROR - Job 351 was killed before it finished (likely due to running out of memory)
