[2022-03-15 10:40:36,093] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:36:00+00:00 [queued]>
[2022-03-15 10:40:36,100] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:36:00+00:00 [queued]>
[2022-03-15 10:40:36,101] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:40:36,101] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-15 10:40:36,101] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 10:40:36,111] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): get_recipes> on 2022-03-15 10:36:00+00:00
[2022-03-15 10:40:36,115] {standard_task_runner.py:52} INFO - Started process 18742 to run task
[2022-03-15 10:40:36,121] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'simple_dag', 'get_recipes', 'scheduled__2022-03-15T10:36:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/simple_dag.py', '--cfg-path', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpolz5anfz', '--error-file', '/var/folders/tl/ljh9dpdd2fnbgmc62qc2b49h0000gn/T/tmpr8bks8ol']
[2022-03-15 10:40:36,124] {standard_task_runner.py:77} INFO - Job 263: Subtask get_recipes
[2022-03-15 10:40:36,185] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_dag.get_recipes scheduled__2022-03-15T10:36:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-03-15 10:40:36,236] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple_dag
AIRFLOW_CTX_TASK_ID=get_recipes
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T10:36:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T10:36:00+00:00
[2022-03-15 10:40:36,252] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 10:40:36,253] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 10:40:36,831] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-15 10:40:36,832] {base_aws.py:90} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2022-03-15 10:40:37,705] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 107, in get_recipes
    dfrecipe = dfrecipe.concat(getRecipe(response.json()['results']), ignore_index=True)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'concat'
[2022-03-15 10:40:37,726] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=get_recipes, execution_date=20220315T103600, start_date=20220315T154036, end_date=20220315T154037
[2022-03-15 10:40:37,736] {standard_task_runner.py:89} ERROR - Failed to execute job 263 for task get_recipes
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/HomeFolder/airflow/dags/simple_dag.py", line 107, in get_recipes
    dfrecipe = dfrecipe.concat(getRecipe(response.json()['results']), ignore_index=True)
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'concat'
[2022-03-15 10:40:37,770] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-15 10:40:37,792] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
